# Generated by Django 5.1 on 2024-08-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseSample",
            fields=[
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        editable=False,
                        help_text="Unique identifier for this sample.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a string of up to 200 characters.", max_length=200, verbose_name="name"
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SampleTypeB",
            fields=[
                (
                    "basesample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="example.basesample",
                    ),
                ),
                (
                    "b_field",
                    models.CharField(
                        help_text="Enter a string of up to 200 characters.", max_length=200, verbose_name="b_field"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample Type B",
                "verbose_name_plural": "Sample Types B",
            },
            bases=("example.basesample",),
        ),
        migrations.CreateModel(
            name="SampleTypeA",
            fields=[
                (
                    "basesample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="example.basesample",
                    ),
                ),
                (
                    "a_field",
                    models.CharField(
                        help_text="Enter a string of up to 200 characters.", max_length=200, verbose_name="a_field"
                    ),
                ),
                (
                    "testr",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="example.sampletypea"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample Type A",
                "verbose_name_plural": "Sample Types A",
            },
            bases=("example.basesample",),
        ),
    ]
