# Generated by Django 5.1 on 2024-08-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0002_alter_basesample_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a string of up to 200 characters.", max_length=200, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Related Model",
                "verbose_name_plural": "Related Models",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a string of up to 200 characters.", max_length=200, verbose_name="name"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="example.basesample"
                    ),
                ),
            ],
            options={
                "verbose_name": "Child",
                "verbose_name_plural": "Children",
            },
        ),
        migrations.AddField(
            model_name="basesample",
            name="related_field",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="example.relatedmodel"
            ),
        ),
    ]
